[2019-12-31 10:20:51,061] [log.py|__console] [line:40] INFO    : 当前执行测试用例ID-> test_login001.1 ; 测试点-> 手机号和密码为空登录
[2019-12-31 10:20:51,660] [log.py|__console] [line:40] INFO    : 检查点-> 用户名不能为空！
[2019-12-31 10:20:51,665] [log.py|__console] [line:40] INFO    : 异常登录，返回实际结果是->: 用户名不能为空！
[2019-12-31 10:20:51,989] [log.py|__console] [line:40] INFO    : 当前执行测试用例ID-> test_login001.2 ; 测试点-> 手机号为空登录
[2019-12-31 10:20:52,304] [log.py|__console] [line:40] INFO    : 检查点-> 用户名不能为空！
[2019-12-31 10:20:52,313] [log.py|__console] [line:40] INFO    : 异常登录，返回实际结果是->: 用户名不能为空！
